name: Build API Cadastro Jogador

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configura Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Cache do Maven (pra acelerar builds)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build do projeto com Maven
      - name: Build with Maven
        run: mvn -B clean package

      # Publica o JAR gerado como artefato do workflow
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: cadastro-jogador-jar
          path: target/cadastro-jogador-0.0.1-SNAPSHOT.jar

